version: "3.6"
services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    networks: [internal]
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: sb_test
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    hostname: pg
  application:
    image: localhost:5000/sb-test:latest
    ports:
      - "1122:1122"
    networks: [internal]
    links:
      - "pg"
networks:
  internal:
    external: { name: internal }
